### PR TITLE
Support Windows directory separator

### PR DESCRIPTION
**Pull request by marktopper**
Thanks to @emptynick for reporting this issue.

### CODE REVIEW

**Comment by fletch3555** [comment]
A little late since this is already merged, but doesn't PHP have a constant that holds the current environment's directory separator? You could simplify it and use that

**Comment by marktopper** [comment]
Properly a good idea @fletch3555. 👍

**Comment by emptynick** [comment]
It does, but `$path` holds something like `\hooks/test-hook/resources\assets\scripts\alert.js` in my case.

**Comment by fletch3555** [comment]
Yeah, I had a feeling that might be the case.  But `$file->getRelativePath()` _shouldn't_ do that... I think it should always return a valid path using on your current file system separator.  Might be worth digging into that and reporting it on the repo for whatever that's coming from (Flysystem?)

**Pull request merged**
